import enforceNullEnvCode from "../autogenerated/bundles/enforceNullEnv.binaryify.js"
import { simpleWorkerEval } from "./generic_helpers/simpleWorkerEval.js"

/**
 * run code in a limited environment that is deterministic. 
 *
 * @note outputs must be clonable (to pass to/through a JS worker)
 * @example
 * ```js
 * let x = await deterministicEval(`10 + new Date().getTime()`)
 * ```
 */
export const deterministicEval = (code, {timeout=Infinity}={})=>simpleWorkerEval({timeout,code,preloadCode:enforceNullEnvCode})