import esbuild from "../vendored/esbuild.js"
import uint8ArrayForEsbuildWasm from "../autogenerated/bundles/esbuild.wasm.binaryified.js"
import { Go } from "./goWasm.js"

const module = (await WebAssembly.instantiate(uint8ArrayForEsbuildWasm, new Go().importObject)).module
await esbuild.initialize({
    wasmModule: module,
    worker: false,
})
export default esbuild